### ISSUE TITLE
About sampling multiple answers

### ISSUE THREAD

**Issue by baoduoxu** [jlko/semantic_uncertainty#5]
Thanks for your great work! 

In the `README.md`, you have mentioned:
> For smaller models (7B parameters), desktop GPUs such as the Nvidia TitanRTX (24 GB) are sufficient.

When I conducted the experiments myself with Model: LLaMA 2 Chat 7B and GPU: GeForce RTX 3090, I modified the `num_return_sequences` parameter to sample multiple answers and use beam search as sampling method, as shown below:
```python
with torch.inference_mode():
    output_ids = model.generate(
        input_ids,
        images=image_tensor,
        do_sample=False,
        temperature=1.0,
        max_new_tokens=512,
        use_cache=True,
        # generate multiple outputs
        num_return_sequences=num_return_sequences, 
        num_beams=num_beams,
        num_beam_groups=1,
        stopping_criteria=[stopping_criteria],
        return_entropies=return_entropies
    )
```

And I also want to return entropies during inference. However, I encountered an out-of-memory issue, as 24 GB of VRAM could only sample up to 7 answers.

I would like to know how many answers you sampled when calculating semantic entropy and naive entropy. What sampling method did you use and how did you sample multiple answers?

Hope to receive your response! Thanks a lot!

**Comment by jlko** [comment]
Hi baoduoxu,

Thanks for your interest in the codebase!

> And I also want to return entropies during inference. However, I encountered an out-of-memory issue, as 24 GB of VRAM could only sample up to 7 answers.

You can always sample sequentially (which is what [we do](https://github.com/jlko/semantic_uncertainty/blob/a8d9aa8cecd5f3bec09b19ae38ab13552e0846f4/semantic_uncertainty/generate_answers.py#L175C1-L182C1)) instead of in parallel, if you seek to minimize GPU memory usage.

> What sampling method did you use and how did you sample multiple answers?

Simple multinomial sampling (with top_p=0.9, top_k=50 as per llama default) at temperature 1. 

Hope this helps!
Jannik
