### ISSUE TITLE
parallel running on multiple gpus with Llama-2-70b

### ISSUE THREAD

**Issue by nguyentuc** [jlko/semantic_uncertainty#8]
Thank you for your very interesting paper. 
In readme, you said that the largest models of 70B parameters require two Nvidia A100 GPUs (2x80GB) simultaneously.  We are evaluating Llama-2-70b with 4 x A100  40VRAM GPUs. However, it seems it is not enough for Llama-2 because it shows me a CUDA out-of-memory error.
Do you have any suggestions on the GPU configuration for evaluating the large models? 

Thank you so much,

**Comment by jlko** [comment]
Hi nguyentuc,

Thanks for your interest in the paper and code!

The current codebase should automatically distribute Llama-2-70B models across _two_ GPUs. However, we're expecting cards with at least 80GB of memory and the code does not currently support cards with less memory. This is why it's OOMing for you.

However, hopefully you should be able to get things running with some small adjustments to the code. For things to work with 40GB cards – where hopefully, you should be able to work with Llama-2-70B across 4 GPUs – you need to adjust the model loading code here (https://github.com/jlko/semantic_uncertainty/blob/a8d9aa8cecd5f3bec09b19ae38ab13552e0846f4/semantic_uncertainty/uncertainty/models/huggingface_models.py#L126-L148).

I hope this helps!
Jannik

**Comment by nguyentuc** [comment]
Thank you for your prompt response. I fixed the problem to run on 4 gpus. However, I have a question about why you set **Only triggers if we find more than one split layer.** in the remove_split_layer function.
Should we remove all split layers?
Thanks,

**Comment by jlko** [comment]
The `remove_split_layer` was necessary because, for me, HuggingFace split a single Transformer layer across multiple GPUs which then caused errors. Perhaps this has been fixed and things will work fine without it now.

If you need to use the remove_split_layer function, you may need to modify it to make sure it works with more than two GPUs.  Perhaps, this is as simple as removing the raise, however, I would suggest you test this carefully. Unfortunately, I cannot remember, why I put this raise in, in the first place.

**Comment by nguyentuc** [comment]
Thank you for your respond!!

**Comment by GaoxiangLuo** [comment]
Hi @nguyentuc, I ran into a similar situation as you did. Would you mind sharing how did you manage to run on 4 GPUs? Thank you!
