### ISSUE TITLE
run compute_uncertainty_measures.py、analyze_results.py individually

### ISSUE THREAD

**Issue by LLLoUo** [jlko/semantic_uncertainty#9]
Hello, in the semantic_uncertainty project, I successfully ran the command `python semantic_uncertainty/generate_answers.py --model_name=Llama-2-7b-chat --dataset=trivia_qa`, and currently have obtained experiment_details.pkl, train_generations.pkl, uncertainty_measures.pkl, validation_generations.pkl, and also reproduced the visualization graph in notebooks/example_evaluation.ipynb.
![屏幕截图 2024-09-19 110358](https://github.com/user-attachments/assets/11bd7668-3a08-4c8c-82e8-c4e664a10715)

I want to run compute_uncertainty_measures.py and analyze_results.py separately to recalculate the results. What do I need to do?

**Comment by jlko** [comment]
Hi LLLoUo,

You can set the `eval_wandb_runid` arg to the wandbid of the run which you wish to evaluate when executing `compute_uncertainty_measures.py`. This should also trigger `analyze_run.py` as the `analyze_run` arg should be True by default. If you wish to store the results to a new wandbid, e.g. because you want to avoid overwriting the old results, make sure to set `assign_new_wandb_id` as well.

We do not support execution from a custom set of files, but, if this is something you require, it should hopefully not be too hard to implement. Lines 90-94 in compute_uncertainty_measures (https://github.com/jlko/semantic_uncertainty/blob/a8d9aa8cecd5f3bec09b19ae38ab13552e0846f4/semantic_uncertainty/compute_uncertainty_measures.py#L90C1-L95C1) should be a good starting point.

Cheers
Jannik
